### ISSUE TITLE
Exploration: Social features

### ISSUE THREAD

**Issue by roydejong** [roydejong/BeatSaberServerBrowser#10]
It could be interesting exploring more social features for multiplayer.

Some notes and thoughts I've had, partially based on some discussions I've seen on the topic:

#### Add players as friends?
When a server goes offline or people leave, you may never see those players again. There's no way to add them as friends in the lobby, and there's no way to see players you've recently encountered.

It could be interesting adding a friend system but that actually presents some technical challenges, not in the least because I'm not sure if multiplayer data even gives us their Steam ID etc right now. If not, that makes this way more complicated (we'd need to extend multiplayer or use the mod's API server) and less useful (only mod users would be able to connect to each other).

#### Joining friends' games
If we can integrate friends, it would be cool to see their status ingame, with an option to join their game if possible.

**Comment by Galacton** [comment]
Two comments:
1. As far as Steam friends go, I'm fairly certain that the name the game uses for multiplayer is the Steam ID of the user as that is what shows up for me and my friend.
2. Even if it isn't, an in-game friends system with some sort of notification sort of like the Oculus notification system that has a fixed, dynamic position in game would be awesome, but I doubt that would be easy or even possible to do with mods because it's something that would need super deep integration.

Either way, literally just making a log file with all the players you have played with and at what time you played with would be a huge step in this direction.

**Comment by roydejong** [comment]
I'm closing this ticket for now, as I don't think it's currently possible to do much in this regard.

### Some closing thoughts

The way multiplayer works, we only have two pieces of data for every player in the lobby:
 1. Their user-id hash (unique within beat saber multiplayer, but meaningless on its own, can't be reversed)
 2. Their username (not unique on Steam, and also apparently can be spoofed on multiplayer)

So in practical terms we can't even reliably know you what distinct player you are playing with.

A newer version of MultiplayerExtensions *does* provide extended user information, i.e. their platform and User ID, so there are opportunities to get this information in the future, but this is rather fragmented and unpredictable -- not many people have this version, and vanilla players never will have it.

So my position on this is:
- Social features are kind of out of scope for BSSB to begin with
- Social features depend on newer MpEx versions, so maybe it's better suited for that mod anyway
- I might consider adding the player list to server browser data so you can at least see is/was in a lobby with you, by name only, but that's more on the website side
