### ISSUE TITLE
Error when joining game: Game does not exist(CFR-5)

### ISSUE THREAD

**Issue by Blixtdraken** [roydejong/BeatSaberServerBrowser#12]
What is says basically. I just get that whenever I try to join somebody in the browser.

**Comment by roydejong** [comment]
What platform are you on, Steam or Oculus?

**Comment by Blixtdraken** [comment]
I am on Oculus platform with a Oculus rift s

**Comment by roydejong** [comment]
Unfortunately most (almost all) games on the server browser are for the Steam platform currently.

CFR-5 indicates, in your case, that you can't join due to cross-play restrictions (the game doesn't exist on oculus multiplayer servers, basically). 

The server browser normally tries to hide incompatible games on other platforms, but because of a minor issue with BS_Utils, it can't always detect the platform correctly so you may see some incompatible games at times.

I wish I had a better answer but unfortunately there's not just enough oculus players on the mod right now to give you a good experience. Cross-play mods are under development though, so the situation will hopefully be better soon.

**Comment by Blixtdraken** [comment]
Ok, thank you! That is very helpful. I might get the game on steam sometime soon either way for other reasons.  Thank you 👍 ☺️
