### ISSUE TITLE
Pitch Black Lobby

### ISSUE THREAD

**Issue by ProdigusProgrammer** [roydejong/BeatSaberServerBrowser#17]
I'm on the 2020 Valve Index with Beat Saber and all required mods (mapping extensions, core mods, etc.) reinstalled today. I tried joining numerous steam modded servers and found that except for my Valve floor bounds, the screen was entirely black. Menu options seemed to exist since waving the controller around caused it to vibrate over invisible buttons. The system button on the controller works and causes the Valve menu to visibly pop up. Any ideas for a potential fix? Btw, I'm left-handed, if that helps. Also, making my own server worked, though no one joined. Computer: Dell Alienware M17 RTX 2070 Super 8GB)
![plugins](https://user-images.githubusercontent.com/74723355/99724479-a7d78800-2a81-11eb-9cf4-256e515ea149.jpg)
![bottom](https://user-images.githubusercontent.com/74723355/99724481-a7d78800-2a81-11eb-89ad-8ff0f04e0419.jpg)
![top](https://user-images.githubusercontent.com/74723355/99724483-a7d78800-2a81-11eb-98d1-185fe94a8d5d.jpg)

**Comment by roydejong** [comment]
The server browser mod only helps the game connect to a lobby, once you get to that black screen it's out of our hands.

Most likely your issue is related to the base game and/or MultiplayerExtensions. These soft locks are known to happen with custom maps sometimes.

I wish I could give you a better answer, but I recommend to keep trying and/or try other servers or levels to join. You may also have a better experience if you try avoiding joining games-in-progress.

I can take a quick look at your log if you want, to see if I can spot anything unusual (`Beat Saber\Logs\_latest.log`).
