### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by KonradIT** [roydejong/BeatSaberServerBrowser#21]
Hey man, good work on this plugin!!

I'm a Quest 2 user and just found that Beat together mod is available for everyone, but Quest users cannot browse the lobbies on the beat saber app itself. The code is easy to read and the JSON API could be useful for a CLI program to push the server code to the quest via ADB (still looking at how, and if beat saber app allows for custom launch intents or clipboard pasting). Is it OK if I use the `https://bssb.app/api` API for my own scripts? Thanks!

**Comment by hpenney2** [comment]
Maybe the API could become open-source as well? (still not sure what security issues that could possibly entail)

**Comment by roydejong** [comment]
I don't have access to or plans for quest development myself currently, so you are absolutely welcome to work on this and use the API. I realize it's undocumented right now, but I hope the client code is straightforward enough. Feel free to get in touch if you need any help beyond that.

**Comment by roydejong** [comment]
I didn't publish the API project initially because I wanted to observe how people used it and whether there were any bad actors. The API project makes it rather obvious how I try to filter out bad requests, so that was the primary consideration. Not so much security issues as "oh god please don't be evil and make this much more complicated than it needs to be". Frankly I haven't seen any issues and you'd have to be a real degenerate to try to ruin this 😉 so:

The API project is now public at https://github.com/roydejong/bssb.app - I'll close this issue up, and if you need any further help with the API feel free to open an issue there.

**Comment by KonradIT** [comment]
Ah, pretty neat, thank you! What I have so far:

![imagen](https://user-images.githubusercontent.com/5891284/103768842-862b6380-5023-11eb-9ba5-2dbfc81cf6b0.png)
