### ISSUE TITLE
ServerBrowser v0.7.4 doesn't show server code in multi menu

### ISSUE THREAD

**Issue by beaudamion** [roydejong/BeatSaberServerBrowser#43]
When you create a modded server for multi on beat together and have server browser enabled  when you create it the server code isn't shown in the multiplayer menu to share out. 

If you create the server and don't share the server on server browser the code will show up... you then have to enable server browser within the multiplayer menu to get it to work

**Comment by roydejong** [comment]
Thanks for the report. It seems this only happens on BeatTogether and not official servers.

I'll need to dive into this a bit deeper to figure out where the issue lies; it may need an update on the BeatTogether server end.

Background: _Connection settings are hidden from view by the game when one of the following conditions is true:
 a) You do not have "invite" permissions; or
 b) The lobby is marked as "Hidden" by the server_

**Comment by roydejong** [comment]
I've pushed a fix to the BT dedicated server: 693184f98cc26497c29fe0050ec84f0c64afb656

This issue will be solved once that's live - likely very soon since they're working on some other fixes as well right now.
