### ISSUE TITLE
[v1-rewrite] NullReferenceException in announce when running with useCustomServerEnvironment set

### ISSUE THREAD

**Issue by rcelyte** [roydejong/BeatSaberServerBrowser#60]
Enabling `useCustomServerEnvironment` in the game's configuration file, the master server can be overridden without the help of additional mods. However, the Harmony patch ServerBrowser uses to detect updates to `masterServerEndPoint` assumes that `INetworkConfig` is bound to `NetworkConfigSO`, which is not the case here. As a result, `Activity.MasterServer` remains unset and `ServerBrowser.Core.GameStateManager.GenerateAnnounce()` fails. One possible fix would involve applying the same patch to the correct binding in this configuration, `CustomNetworkConfig`, allowing changes to be detected there as well.

**Comment by roydejong** [comment]
Thanks, I'll take this into consideration and test this scenario when finalizing the rewrite.

v1-rewrite will depend on MultiplayerCore and I think some changes may be needed there to better accommodate things like custom network configs, as well as the "new" official multiplayer architecture (GameLift).

**Comment by roydejong** [comment]
I've updated the rewrite branch to refer to `INetworkConfig` directly for master server detection: 324d032fe2b346880a79219d0fbee7cf6fa51498

This is the cleanest way for this mod to read config data because it supports other implementations like `CustomNetworkConfig` while still also being subjected to MultiplayerCore's patches.

Note: master server switching in the server browser (when joining a game on another master) will not work for users with a `CustomNetworkConfig` because MultiplayerCore does not currently support patching it, but that's out of my scope. If this is an important use case it may be good to open an issue there separately
